# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Tom's Github settings
# title: Calm Meditation
# baseurl: /calm-meditation
# url: http://idratherbewriting.com
# baseurl_media: http://idratherassets.com/calm-meditation/
# github_username:  tomjohnson1492
# author: Tom Johnson
# email: tom@idratherbewriting.com

# Amazon AWS settings

title: Calm Meditation
email: devcomm-appstore@amazon.com
url: http://sample-firetv-web-app.s3-website-us-west-2.amazonaws.com
baseurl_media: http://d1nixf144dcz0j.cloudfront.net/
github_username:  amzn-tomjoht
author: Amazon
logo: calmmeditationlogo_small.png
copyright_license:
copyright_url: https://creativecommons.org/licenses/by/4.0/



logo: calmmeditationlogo_small.png
theme: minima
# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

description: >
  Contains short videos capturing still scenes from nature with a music background,
  intended for calming or meditation purposes. When you're stressed out or upset, watch
  a few videos. As your mind focuses on the small details, let your worries and frustrations
  float away. The purpose is not to entertain or to distract, but to help calm, soothe, and
  surface your inner quiet. The videos contain scenes from the San Tomas Aquinas trail
  in Santa Clara, California. (Note: The real purpose of these videos is to supply content for this test app.)
